#+ summary: Give me some information about the registers 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET#+ tags:
#+   - table
#+   - archive

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

SELECT ?reg STR(?label) AS ?label ?start ?end STR(?pageNb) AS ?pageNb
WHERE 
{ ?reg a meta:Register ; sem:hasBeginTimeStamp  ?start ;  sem:hasEndTimeStamp ?end ; rdfs:label ?label ; dhc:pageCount ?pageNb .}
ORDER BY ?reg
