#+ summary: Give me all contracts before year x. 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+  - 01_archive
# params: ?_date

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX meta: <http://vocab.dhlab.epfl.ch/archive-metadata#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dhc: <http://vocab.dhlab.epfl.ch/dhcanvas#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/> 

SELECT (COUNT (?contract) AS ?NbContracts)
WHERE {
  ?contract a grz-owl:Contract ; sem:hasTimeStamp ?date .
  BIND(IF(?date = "0"^^<http://www.w3.org/2001/XMLSchema#gYear>,"NO DATE", xsd:dateTime(?date) ) AS ?myDate) 
  FILTER (?myDate < '?_date'^^xsd:dateTime)
}
