#+ summary:  Give me all mentions of person entity with id x. 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+   - list
#+   - mentions

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

SELECT ?pm
WHERE
{
     ?pe a common:Person ; core:referredBy ?pm ; dhc:uuid '76b3eb35-6b08-4a51-adfe-13495667ca53' .
     ?pm a common:PersonMention 
}
