#+ summary: What is the distribution of roles of person entities mentioned more than X times? 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+	- mentions
#+ params: ?_times

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

SELECT  ?roleType COUNT (distinct ?pe)
WHERE
{
	{

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>

	    SELECT ?pe WHERE
	    { ?pm a common:PersonMention ; core:refersTo ?pe . }
	    GROUP BY ?pe 
	    HAVING (count(distinct ?pm) > ?_times)
	}
	?pe grz-owl:hasRole/rdf:value ?roleType .
}
GROUP BY ?roleType 
