#+ summary: In which profession the salary is payed by the master, by the apprentice? (using profession standard forms) 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+  - 08_salaries

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX meta: <http://vocab.dhlab.epfl.ch/archive-metadata#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dhc: <http://vocab.dhlab.epfl.ch/dhcanvas#>
PREFIX foaf: <http://xmlns.com/foaf/0.1>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/> 

SELECT ?profSF  ?NbSalPaidByApp ?NbSalPaidByMaster
WHERE
{
  {SELECT ?profSF (COUNT (distinct ?sal) AS ?NbSalPaidByApp) 
  WHERE {
    ?c core:hasMention ?master ; grz-owl:hasCondition ?sal .
    ?sal a grz-owl:FinancialCondition ; grz-owl:paidBy grz-owl:ApprenticePayer.
    ?master a common:PersonMention ; grz-owl:hasRole grz-owl:Master ; grz-owl:hasProfession ?prof . ?prof common:standardForm ?profSF .
    } GROUP BY ?profSF }
  {SELECT ?profSF (COUNT (distinct ?sal) AS ?NbSalPaidByMaster) 
  WHERE {
    ?c core:hasMention ?master ; grz-owl:hasCondition ?sal .
    ?sal a grz-owl:FinancialCondition ; grz-owl:paidBy grz-owl:MasterPayer.
    ?master a common:PersonMention ; grz-owl:hasRole grz-owl:Master ; grz-owl:hasProfession ?prof . ?prof common:standardForm ?profSF .
    } GROUP BY ?profSF }
}
GROUP BY ?profSF
ORDER BY ASC(?profSF)
