#+ summary: Overview of the locations of charges 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+   - charges 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX meta: <http://vocab.dhlab.epfl.ch/archive-metadata#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dhc: <http://vocab.dhlab.epfl.ch/dhcanvas#>
PREFIX foaf: <http://xmlns.com/foaf/0.1>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/> 

SELECT (STR(?chargeTranscript) AS ?chargeTranscript) (STR(?locationTranscript) AS ?locationTranscript) ?parish ?sestriere
WHERE
{
  ?charge  a grz-owl:ChargeMention .
  ?charge common:transcript ?chargeTranscript .
  ?charge  grz-owl:hasLocation ?location .
  ?location common:transcript ?locationTranscript .
  OPTIONAL {?location common:inParish ?chargeParish . ?chargeParish rdfs:label ?parish ; common:inSestriere ?chargeSestriere  .    ?chargeSestriere rdfs:label ?sestriere}
}
