#+ summary: Give me all apprentices, along with their related information, whose profession contains the string "servir" (could also be another string) 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+   - professions 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX meta: <http://vocab.dhlab.epfl.ch/archive-metadata#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dhc: <http://vocab.dhlab.epfl.ch/dhcanvas#>
PREFIX foaf: <http://xmlns.com/foaf/0.1>
PREFIX iiif: <http://iiif.io/api/presentation/2#>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/> 

SELECT (STR(?contractUUID) AS ?contractUUID) (STR(?appUUID) AS ?appUUID) ?DHCLink 
(?app AS ?appLODVIEW) (STR(?appLabel) AS ?appLabel) (GROUP_CONCAT(?otherProfTR;separator=" // ") as ?appProfTranscripts) 
(STR(?g) AS ?gender) ?age (STR(?at) AS ?ageText) (STR(?appGeoOriginTranscript) AS ?appGeoOriginTranscript) 
(STR(?appGeoOriginStandardForm) AS ?appGeoOriginStandardForm ) (STR(?ptMaster) AS ?profMasterTranscript) 
(STR(?ptsf) AS ?profMasterStandardForm) ?year (STR(?date) AS ?fullDate)
WHERE
{
	# info app
	?app dhc:uuid ?appUUID ; core:isMentionedIn ?contract ; grz-owl:hasName ?n . ?n rdfs:label ?appLabel .
        OPTIONAL {?app foaf:gender ?g .}
	OPTIONAL {?app foaf:age ?age }
	OPTIONAL {?app grz-owl:ageText ?at }
        OPTIONAL {?app grz-owl:hasGeographicalOrigin ?appGeoOrigin.
                 ?appGeoOrigin common:transcript ?appGeoOriginTranscript .
                 OPTIONAL {?appGeoOrigin common:standardForm ?appGeoOriginStandardForm} }
	# get other professions
        OPTIONAL {?app grz-owl:hasProfession ?otherProf .
	?otherProf common:transcript ?otherProfTR .}
	# info contract
	?contract a grz-owl:Contract; dhc:uuid ?contractUUID ; sem:hasTimeStamp ?date ; ^edm:realizes ?page ; core:hasMention ?master .
	?page a meta:Page; meta:isImagedBy ?x . ?x iiif:service ?DHCLink .
	BIND (year(?date) AS ?year).
        # info master 
        ?master grz-owl:hasRole grz-owl:Master ; grz-owl:hasProfession ?profMaster .
        ?profMaster common:transcript ?ptMaster .
        OPTIONAL { ?profMaster common:standardForm ?ptsf.}
	# nested query to select app with "servir"
	{SELECT ?app  ?profTR
	WHERE {?app a common:PersonMention ;  grz-owl:hasRole grz-owl:Apprentice ;  grz-owl:hasProfession ?prof.
		?prof common:transcript ?profTR .
		?profTR bif:contains "'servir*'".}
	}
}
ORDER BY ASC(?date) ?appLabel
