#+ summary: Display TR/SF/CAT of all profession mentions, grouped and alphabetically ordered by transcripts 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+  - 10_profession normalisation 

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX meta: <http://vocab.dhlab.epfl.ch/archive-metadata#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dhc: <http://vocab.dhlab.epfl.ch/dhcanvas#>
PREFIX foaf: <http://xmlns.com/foaf/0.1>
PREFIX iiif: <http://iiif.io/api/presentation/2#>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/> 

SELECT ?ProfTrancript ?ProfStandardFrom ?ProfCategory
WHERE 
{
  ?prof a grz-owl:ProfessionMention; common:transcript ?ProfTrancript .
  OPTIONAL {?prof common:standardForm ?ProfStandardFrom .}
  OPTIONAL {?prof grz-owl:professionCategory ?ProfCategory .}
}
GROUP BY ?ProfTrancript
ORDER BY ASC(?ProfTrancript)
