#+ summary: How many flees are there, with and without denunciation date? 
#+ endpoint: http://128.178.60.47:8890/sparql
#+ method: GET
#+ tags:
#+  - 15_events

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://vocab.dhlab.epfl.ch/data-core#>
PREFIX common: <http://vocab.dhlab.epfl.ch/data-common#>
PREFIX grz-owl: <http://vocab.dhlab.epfl.ch/garzoni#>
PREFIX meta: <http://vocab.dhlab.epfl.ch/archive-metadata#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dhc: <http://vocab.dhlab.epfl.ch/dhcanvas#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/> 

SELECT ?FleeWithDenunciationDate ?FleeWithoutDenunciationDate
WHERE 
{
 {SELECT (COUNT (distinct ?e)  AS ?FleeWithDenunciationDate )
 WHERE {?e sem:eventType grz-owl:Flee ; grz-owl:denunciationDate ?denunDate .}}
 {SELECT (COUNT (distinct ?e)  AS ?FleeWithoutDenunciationDate )
 WHERE {?e sem:eventType grz-owl:Flee . FILTER( NOT EXISTS { ?e grz-owl:denunciationDate ?denunDate } )}}
}
